### ISSUE TITLE
Xamarin: Not able to build the Android WalkMe binding project after adding Xamarin.Androidx.Room.Runtime

### ISSUE THREAD

**Issue by kabinesh** [abbiio/androidsdk#1]
Hi Everyone.

Getting following build error after adding Xamarin.Androidx.Room.Runtime and its dependent packages.

`obj\Debug\generated\src\Abbi.IO.Abbisdk.DB.WMDatabase_Impl.cs(56,165,56,187): error CS0507: 'WMDatabase_Impl.RequiredTypeConverters': cannot change access modifiers when overriding 'protected' inherited member 'RoomDatabase.RequiredTypeConverters'
obj\Debug\generated\src\Abbi.IO.Abbisdk.DB.WMDatabase_Impl.cs(82,68,82,93): error CS0507: 'WMDatabase_Impl.CreateInvalidationTracker()': cannot change access modifiers when overriding 'protected' inherited member 'RoomDatabase.CreateInvalidationTracker()'
obj\Debug\generated\src\Abbi.IO.Abbisdk.DB.WMDatabase_Impl.cs(94,78,94,94): error CS0507: 'WMDatabase_Impl.CreateOpenHelper(DatabaseConfiguration)': cannot change access modifiers when overriding 'protected' inherited member 'RoomDatabase.CreateOpenHelper(DatabaseConfiguration)'`

Tried with WalkMe SDK versions 2.13.1 and 2.12.5, both showing same errors.

Can anyone help me to solve this?

**Comment by yairb** [comment]
Hi @kabinesh 

Try changing manually the modifiers in those 3 places, from 'public' to 'protected'

**Comment by kabinesh** [comment]
Hi @yairb,

Thank you for your response. Those errors are from generated files in obj folder. I hope it is not possible to change, even if we change it next time when build the binding project it will be gone.

I am using WalkMe sdk in xamarin application as Binding project (https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/binding-an-aar#using-the-bindings-library)

**Comment by yairb** [comment]
@kabinesh 

Hey

I wrote you this solution, to change the generated files, cause I remember that solved it once for me. It's not ideal, of course.
 I'm not sure why xamarin change the modifiers this way. 
I'll look into it later today, to find a better solution.

**Comment by kabinesh** [comment]
@yairb 

I found the solution for the problem. We need to update the visibility of the method using Metadata.xml in binding project.

https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/troubleshooting-bindings#problem-name-collisions-on-inner-classes--properties

Here is the change to be updated in metadata.

` <attr path="/api/package[@name='abbi.io.abbisdk.db']/class[@name='WMDatabase_Impl']/method[@name='createInvalidationTracker']" name="visibility">protected</attr>
  <attr path="/api/package[@name='abbi.io.abbisdk.db']/class[@name='WMDatabase_Impl']/method[@name='createOpenHelper']" name="visibility">protected</attr>
  <attr path="/api/package[@name='abbi.io.abbisdk.db']/class[@name='WMDatabase_Impl']/method[@name='getRequiredTypeConverters']" name="visibility">protected</attr>`
